spring:
  application:
    name: sgd
 # profiles:
 #  active: local
  datasource:
    url: jdbc:mysql://localhost:3306/bd_sgd?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 123
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 1
      minimum-idle: 1
      leakDetectionThreshold: 60000
      keepaliveTime: 30000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: validate  # Pode ser 'none', 'update', 'create', 'create-drop' conforme sua necessidade
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#      date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
server:
  port: ${PORT:8081}
  tomcat:
    connection-timeout: 5000
    threads:
      max: 1
      min-spare: 1
    accept-count: 1

#logging:
#  level:
#    org.springframework.jdbc.datasource: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
#    org.hibernate.orm.connections.pooling: DEBUG


api:
  basePath: "/api"
  domain:
    users:
      path: "/users"
      endpoints:
        findByEmail: "/findByEmail"
    domain:
      path: "/domain"
      endpoints:
        finByAllFilters: "/findByAllFilters"
    shift:
      path: "/shift"
      endpoints: