spring:
  application:
    name: sgd
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password: 123
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 1
      minimum-idle: 1
      leakDetectionThreshold: 60000
      keepaliveTime: 30000
      pool-name: HikariCP
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate  # Pode ser 'none', 'update', 'create', 'create-drop' conforme sua necessidade
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: ${PORT:8081}
  tomcat:
    connection-timeout: 5000
    threads:
      max: 1
      min-spare: 1
    accept-count: 1

#logging:
#  level:
#    org.springframework.jdbc.datasource: DEBUG
#    org.hibernate: DEBUG
#    org.hibernate.orm.connections.pooling: DEBUG


api:
  basePath: "/api"
  domain:
    users:
      path: "/users"
      endpoints:
        findByEmail: "/findByEmail"